dataset_root_dir: './data/totalcapture/'
db_out_dir: './data/images'
action_map: {'rom':1, 'walking':2, 'acting':3, 'running':4, 'freestyle':5}
action_reverse_map: {1: 'rom', 2: 'walking', 3: 'acting', 4: 'running', 5: 'freestyle'}
subjects:
  - 1
  - 2
  - 3
  - 4
  - 5

train_subs:
  - 1
  - 2
  - 3
train_seqs:
  {'rom':[1,2,3], 'walking':[1,3], 'acting':[1,2], 'running':[], 'freestyle':[1,2]}


test_subs:
  - 1
  - 2
  - 3
  - 4
  - 5
test_seqs:
  {'rom':[], 'walking':[2], 'acting':[3], 'running':[], 'freestyle':[3]}

gen_train: true
gen_test: true

save_visualization: false
save_frame: true  # save video frame to disk

joints_filter:  # define which joints to use and the order
  ['Hips', 'RightUpLeg', 'RightLeg', 'RightFoot', 'LeftUpLeg', 'LeftLeg', 'LeftFoot',
   'Spine', 'Neck', 'Head', 'LeftArm', 'LeftForeArm', 'LeftHand', 'RightArm', 'RightForeArm', 'RightHand']

joints_children:
  [[1,4,7], [2], [3], [], [5], [6], [], [8], [9,10,13], [], [11], [12], [], [14], [15], []]
